// Copyright (c) Allors bv. All Rights Reserved.
// Licensed under the LGPL-3.0 License. See LICENSE in the project root for license information.

namespace Allors.Tram.Tests;

using Allors.Tram.Schema;
using Allors.Tram.Schema.Config;
using Allors.Tram.Tests.Fixture;

public static class SchemaFixture
{
    public static TramSchema Schema { get; } = new TramSchema(CreateTramSchemaConfig());

    public static TestsM M { get; } = new TestsM(Schema);

    public static TramSchemaConfig CreateTramSchemaConfig() => new TramSchemaConfigBuilder()
        .AddValueType("DateTime")
        .AddValueType("String")
        .AddValueType("Integer")
        .AddValueType("Boolean")
        .AddInterface("I1", ["I12", "S1"])
        .AddInterface("I2", ["I12", "S2"])
        .AddInterface("I12")
        .AddInterface("S1", ["I12"])
        .AddInterface("S2", ["I12"])
        .AddClass("C1", ["I1"])
        .AddClass("C2", ["I2"])
        .AddClass("C3")
        .AddClass("C4")
        // Same
        .AddAttribute("C1", "String", "Same")
        .AddAttribute("C2", "String", "Same")
        // String
        .AddAttribute("I1", "String", "I1AllorsString")
        .AddAttribute("I2", "String", "I2AllorsString")
        .AddAttribute("I12", "String", "I12AllorsString")
        .AddAttribute("S1", "String", "S1AllorsString")
        .AddAttribute("S2", "String", "S2AllorsString")
        .AddAttribute("C1", "String", "C1AllorsString")
        .AddAttribute("C2", "String", "C2AllorsString")
        .AddAttribute("C3", "String", "C3AllorsString")
        .AddAttribute("C4", "String", "C4AllorsString")
        .AddAttribute("C1", "String", "SameAllorsString")
        .AddAttribute("C2", "String", "SameAllorsString")
        .AddAttribute("C3", "String", "SameAllorsString")
        .AddAttribute("C4", "String", "SameAllorsString")
        // Integer
        .AddAttribute("I1", "Integer", "I1AllorsInteger")
        .AddAttribute("I2", "Integer", "I2AllorsInteger")
        .AddAttribute("I12", "Integer", "I12AllorsInteger")
        .AddAttribute("S1", "Integer", "S1AllorsInteger")
        .AddAttribute("S2", "Integer", "S2AllorsInteger")
        .AddAttribute("C1", "Integer", "C1AllorsInteger")
        .AddAttribute("C2", "Integer", "C2AllorsInteger")
        .AddAttribute("C3", "Integer", "C3AllorsInteger")
        .AddAttribute("C4", "Integer", "C4AllorsInteger")
        .AddAttribute("C1", "Integer", "SameAllorsInteger")
        .AddAttribute("C2", "Integer", "SameAllorsInteger")
        .AddAttribute("C3", "Integer", "SameAllorsInteger")
        .AddAttribute("C4", "Integer", "SameAllorsInteger")
        // Boolean
        .AddAttribute("I1", "Boolean", "I1AllorsBoolean")
        .AddAttribute("I2", "Boolean", "I2AllorsBoolean")
        .AddAttribute("I12", "Boolean", "I12AllorsBoolean")
        .AddAttribute("S1", "Boolean", "S1AllorsBoolean")
        .AddAttribute("S2", "Boolean", "S2AllorsBoolean")
        .AddAttribute("C1", "Boolean", "C1AllorsBoolean")
        .AddAttribute("C2", "Boolean", "C2AllorsBoolean")
        .AddAttribute("C3", "Boolean", "C3AllorsBoolean")
        .AddAttribute("C4", "Boolean", "C4AllorsBoolean")
        .AddAttribute("C1", "Boolean", "SameAllorsBoolean")
        .AddAttribute("C2", "Boolean", "SameAllorsBoolean")
        .AddAttribute("C3", "Boolean", "SameAllorsBoolean")
        .AddAttribute("C4", "Boolean", "SameAllorsBoolean")
        // OneToOne
        .AddOneToOne("C1", "C1", "C1C1OneToOne")
        .AddOneToOne("C1", "C2", "C1C2OneToOne")
        .AddOneToOne("C1", "C3", "C1C3OneToOne")
        .AddOneToOne("C1", "C4", "C1C4OneToOne")
        .AddOneToOne("C1", "I1", "C1I1OneToOne")
        .AddOneToOne("C1", "I2", "C1I2OneToOne")
        .AddOneToOne("C1", "I12", "C1I12OneToOne")
        .AddOneToOne("C1", "S1", "C1S1OneToOne")
        .AddOneToOne("C1", "S2", "C1S2OneToOne")
        .AddOneToOne("C3", "C1", "C3C1OneToOne")
        .AddOneToOne("C3", "C2", "C3C2OneToOne")
        .AddOneToOne("C3", "C3", "C3C3OneToOne")
        .AddOneToOne("C3", "C4", "C3C4OneToOne")
        .AddOneToOne("C3", "I1", "C3I1OneToOne")
        .AddOneToOne("C3", "I2", "C3I2OneToOne")
        .AddOneToOne("C3", "I12", "C3I12OneToOne")
        .AddOneToOne("C3", "S1", "C3S1OneToOne")
        .AddOneToOne("C3", "S2", "C3S2OneToOne")
        // OneToMany
        .AddOneToMany("C1", "C1", "C1C1OneToMany")
        .AddOneToMany("C1", "C2", "C1C2OneToMany")
        .AddOneToMany("C1", "C3", "C1C3OneToMany")
        .AddOneToMany("C1", "C4", "C1C4OneToMany")
        .AddOneToMany("C1", "I1", "C1I1OneToMany")
        .AddOneToMany("C1", "I2", "C1I2OneToMany")
        .AddOneToMany("C1", "I12", "C1I12OneToMany")
        .AddOneToMany("C1", "S1", "C1S1OneToMany")
        .AddOneToMany("C1", "S2", "C1S2OneToMany")
        .AddOneToMany("C3", "C1", "C3C1OneToMany")
        .AddOneToMany("C3", "C2", "C3C2OneToMany")
        .AddOneToMany("C3", "C3", "C3C3OneToMany")
        .AddOneToMany("C3", "C4", "C3C4OneToMany")
        .AddOneToMany("C3", "I1", "C3I1OneToMany")
        .AddOneToMany("C3", "I2", "C3I2OneToMany")
        .AddOneToMany("C3", "I12", "C3I12OneToMany")
        .AddOneToMany("C3", "S1", "C3S1OneToMany")
        .AddOneToMany("C3", "S2", "C3S2OneToMany")
        // ManyToOne
        .AddManyToOne("C1", "C1", "C1C1ManyToOne")
        .AddManyToOne("C1", "C2", "C1C2ManyToOne")
        .AddManyToOne("C1", "C3", "C1C3ManyToOne")
        .AddManyToOne("C1", "C4", "C1C4ManyToOne")
        .AddManyToOne("C1", "I1", "C1I1ManyToOne")
        .AddManyToOne("C1", "I2", "C1I2ManyToOne")
        .AddManyToOne("C1", "I12", "C1I12ManyToOne")
        .AddManyToOne("C1", "S1", "C1S1ManyToOne")
        .AddManyToOne("C1", "S2", "C1S2ManyToOne")
        .AddManyToOne("C3", "C1", "C3C1ManyToOne")
        .AddManyToOne("C3", "C2", "C3C2ManyToOne")
        .AddManyToOne("C3", "C3", "C3C3ManyToOne")
        .AddManyToOne("C3", "C4", "C3C4ManyToOne")
        .AddManyToOne("C3", "I1", "C3I1ManyToOne")
        .AddManyToOne("C3", "I2", "C3I2ManyToOne")
        .AddManyToOne("C3", "I12", "C3I12ManyToOne")
        .AddManyToOne("C3", "S1", "C3S1ManyToOne")
        .AddManyToOne("C3", "S2", "C3S2ManyToOne")
        // ManyToMany
        .AddManyToMany("C1", "C1", "C1C1ManyToMany")
        .AddManyToMany("C1", "C2", "C1C2ManyToMany")
        .AddManyToMany("C1", "C3", "C1C3ManyToMany")
        .AddManyToMany("C1", "C4", "C1C4ManyToMany")
        .AddManyToMany("C1", "I1", "C1I1ManyToMany")
        .AddManyToMany("C1", "I2", "C1I2ManyToMany")
        .AddManyToMany("C1", "I12", "C1I12ManyToMany")
        .AddManyToMany("C1", "S1", "C1S1ManyToMany")
        .AddManyToMany("C1", "S2", "C1S2ManyToMany")
        .AddManyToMany("C3", "C1", "C3C1ManyToMany")
        .AddManyToMany("C3", "C2", "C3C2ManyToMany")
        .AddManyToMany("C3", "C3", "C3C3ManyToMany")
        .AddManyToMany("C3", "C4", "C3C4ManyToMany")
        .AddManyToMany("C3", "I1", "C3I1ManyToMany")
        .AddManyToMany("C3", "I2", "C3I2ManyToMany")
        .AddManyToMany("C3", "I12", "C3I12ManyToMany")
        .AddManyToMany("C3", "S1", "C3S1ManyToMany")
        .AddManyToMany("C3", "S2", "C3S2ManyToMany")
        // Special
        .AddClass("Organization")
        .AddAttribute("Organization", "String", "Name")
        .AddOneToOne("Organization", "Person", "Owner")
        .AddManyToOne("Organization", "Person", "Accountant")
        .AddOneToMany("Organization", "Person", "Employee")
        .AddManyToMany("Organization", "Person", "Customer")
        .AddClass("Person")
        .AddAttribute("Person", "String", "FirstName")
        .AddAttribute("Person", "String", "LastName")
        .AddAttribute("Person", "String", "FullName")
        .AddAttribute("Person", "DateTime", "DerivedAt")
        .AddAttribute("Person", "String", "Greeting")
        .Build();
}
